# Generated by Django 5.1.1 on 2024-10-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='artiste',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='realisateur',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='createur',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(max_length=1000),
        ),
    ]
