# Generated by Django 5.1.1 on 2024-10-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaires', '0002_alter_cd_artiste_alter_dvd_realisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='emprunteur',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='livre',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
