# Generated by Django 5.1.1 on 2024-10-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaires', '0003_alter_cd_name_alter_dvd_name_alter_emprunteur_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jeudeplateau',
            old_name='createur',
            new_name='editeur',
        ),
    ]
